/**: # wildcard for the node name
  ros__parameters:
    has_front_camera: false
    has_vertical_camera: true
    vertical_camera:
      x: 0.15
      y: 0.0
      z: 0.0
      qw: 0.7071068
      qx: 0.0
      qy: 0.7071068
      qz: 0.0
