generation:
  algorithm: LemniscateOfBernoulli
  bounds:
    x: 2.5
    y: 1
  scale: 1
  swap_xy: true
  offset:
    x: 1
    y: 2
    z: -0.69999999999999996
loop: true
waypoints:
  - x: 1.0
    y: -10.0
    z: -0.5
  - x: 1.0
    y: 0.0
    z: -0.5
  - x: 1.0
    y: -10.0
    z: -0.5
  - x: 1.0
    y: 10.0
    z: -0.5
