/**: # wildcard for the node name
  ros__parameters:
    thrust_min: 0.0
    thrust_max: 24.0
    thrust_min_at_target: 1.0
    thrust_max_at_target: 5.0
    body_rate_max: 6.0
    lookahead_thrust: 1.0
    lookahead_attitude: 5.0
    lookahead_body_rate: 1.0
    enable_position_check: true
    mass_rb: 2.31
    mass_added: 0.0
    damping: 2.0
    t_final: 5.0
    gain_position: 10.0
    gain_velocity: 10.0
    timestep_min: 0.02
    continuous: true
    use_attitude_control: true
    generation_update_period: 0.5
    open_loop_threshold_time: 5.0
    gravity:
      x: 0.0
      y: 0.0
      z: 0.0
    target_p0:
      x: 1.0
      y: 1.0
      z: -0.4
    target_v0:
      x: 0.0
      y: 0.0
      z: 0.0
    target_radius: 0.15
    target_yaw: 1.57
    target_pitch: 0.0
    homing_thrust: 5.0
    home_tolerance: 0.1
    home_position:
      x: 0.5
      y: 2.5
      z: -0.6
    home_yaw: 0.0
    home_axis_tolerance: 0.2
    min_wall_distance:
      x: 0.0
      y: 0.0
      z: 0.0
    time_tolerance: 0.5
