#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
import pigpio
from rcl_interfaces.msg import SetParametersResult


class CameraServo(Node):

    def __init__(self, node_name):
        super().__init__(node_name=node_name)
        self.timed_out = False

        self.pi = pigpio.pi()
        self.camer_servo_pin = 20
        self.command_timeout = 0.5

        self.timeout_timer = self.create_timer(self.command_timeout,
                                               self.on_timeout)
        self.declare_parameter('tilt', 50)
        self.add_on_set_parameters_callback(self.on_parameters)

    def on_parameters(self, params):
        for param in params:
            if param.name == 'tilt':
                self.set_servo(param.value / 100.0)
        return SetParametersResult(successful=True)

    def set_servo(self, value: float):
        val = 1500 + value * 400.0
        val = min(1900, max(1100, val))
        self.pi.set_servo_pulsewidth(self.camer_servo_pin, val)

    def on_shutdown(self):
        self.pi.set_servo_pulsewidth(self.camer_servo_pin, 0)


def main():
    rclpy.init()
    node = CameraServo('camera_servo')
    try:
        rclpy.spin(node)
    except:
        pass
    finally:
        node.on_shutdown()


if __name__ == '__main__':
    main()
