#!/usr/bin/env python3

# Copyright (C) 2023 Thies Lennart Alff
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA

import pigpio
import rclpy
from rcl_interfaces.msg import (
    IntegerRange,
    ParameterDescriptor,
    ParameterType,
    SetParametersResult,
)
from rclpy.node import Node
from rclpy.parameter import Parameter
from std_msgs.msg import Float64


class SpotLight(Node):
    def __init__(self, node_name):
        super().__init__(node_name=node_name)
        self.timed_out = False

        self.pi = pigpio.pi()
        self.spotlight_pin = 21

        descr = ParameterDescriptor()
        range = IntegerRange()
        range.from_value = 0
        range.to_value = 100
        range.step = 1
        descr.integer_range = [range]
        descr.type = ParameterType.PARAMETER_INTEGER
        self.declare_parameter('brightness', 50, descr)
        self.add_on_set_parameters_callback(self.on_parameters)
        self.brightness_sub = self.create_subscription(
            Float64, '~/brightness', self.on_brightness, 10
        )

    def on_parameters(self, params):
        for param in params:
            if param.name == 'brightness':
                self.set_servo(param.value / 100.0)
        return SetParametersResult(successful=True)

    def set_servo(self, value: float):
        val = 1100 + value * 800.0
        val = min(1900, max(1100, val))
        self.pi.set_servo_pulsewidth(self.spotlight_pin, val)

    def on_shutdown(self):
        self.pi.set_servo_pulsewidth(self.spotlight_pin, 0)

    def on_brightness(self, msg: Float64):
        value = min(1.0, max(0.0, msg.data))
        self.set_servo(value)
        param = Parameter(
            'brightness', Parameter.Type.INTEGER, int(value * 100.0)
        )
        self.set_parameters([param])


def main():
    rclpy.init()
    node = SpotLight('spotlight')
    try:
        rclpy.spin(node)
    except Exception as e:
        print(f'{e}')
    finally:
        node.on_shutdown()


if __name__ == '__main__':
    main()
