/**: # wildcard for the node name
  ros__parameters:
    channels:
      roll: 0
      pitch: 1
      yaw: 2
      thrust: 3
      vertical_thrust: 4
      lateral_thrust: 5
      reserved_0: 6
      reserved_1: 7

    # OUTPUT = MixerMatrix * INPUT
    # 8x1 = 8x8 * 8x1

    mixer_matrix: [
      -0.25, +0.25, -0.25, +0.25, +0.00, +0.00, +0.00, +0.00,
      -0.25, -0.25, -0.25, -0.25, +0.00, +0.00, +0.00, +0.00,
      -0.25, -0.25, +0.25, +0.25, +0.00, +0.00, +0.00, +0.00,
      -0.25, +0.25, +0.25, -0.25, +0.00, +0.00, +0.00, +0.00,
      +0.00, +0.00, +0.00, +0.00, +0.00, +0.00, +0.00, +0.00,
      +0.00, +0.00, +0.00, +0.00, +0.00, +0.00, +0.00, +0.00,
      +0.00, +0.00, +0.00, +0.00, +0.00, +0.00, +0.00, +0.00,
      +0.00, +0.00, +0.00, +0.00, +0.00, +0.00, +0.00, +0.00,
      ]

    limit_matrix: [
     +1.0, +1.0, +1.0, +1.0, +0.0, +0.0, +0.0, +0.0,
     +1.0, +1.0, +1.0, +1.0, +0.0, +0.0, +0.0, +0.0,
     +1.0, +1.0, +1.0, +1.0, +0.0, +0.0, +0.0, +0.0,
     +1.0, +1.0, +1.0, +1.0, +0.0, +0.0, +0.0, +0.0,
     +1.0, +1.0, +1.0, +1.0, +0.0, +0.0, +0.0, +0.0,
     +1.0, +1.0, +1.0, +1.0, +0.0, +0.0, +0.0, +0.0,
     +1.0, +1.0, +1.0, +1.0, +0.0, +0.0, +0.0, +0.0,
     +1.0, +1.0, +1.0, +1.0, +0.0, +0.0, +0.0, +0.0,
    ]
    # Thrust is assumed to be a quadratic function of revs per second.
    quadratic_coefficient: 2.6e-3
    linear_coefficient: 4.2e-2
    max_rotations_per_second: 50.0
