/**: # wildcard for the node name
  ros__parameters:
    feedthrough: false
    gain:
      roll:
        p: 1.0
        d: 0.3
      pitch:
        p: 1.0
        d: 0.3
      yaw:
        p: 1.0
        d: 0.3
