/**: # wildcard for the node name
  ros__parameters:
    feedthrough: false
    gain:
      roll:
        p: 5.0
        d: 1.0
      pitch:
        p: 5.0
        d: 1.0
      yaw:
        p: 5.0
        d: 1.0
