/**: # wildcard for the node name
  ros__parameters:
    model:
      damping:
        linear:
          # surge: 5.39
          # roll: 0.00174
          # pitch: 0.007
          # yaw: 0.007
          surge: 0.0
          roll: 0.0
          pitch: 0.0
          yaw: 0.0
      inertia:
        # surge: 3.42
        # roll: 0.007
        # pitch: 0.027
        # yaw: 0.027
        surge: 1.0
        roll: 1.0
        pitch: 1.0
        yaw: 1.0
    gains:
      p:
        surge: 1.0
        roll: 0.05
        pitch: 0.07
        yaw: 0.07
    # single failure
    phase_order: [2, 3, 5]
    # double failure
    # phase_order: [2, 4, 6]
    # phase_order: [6, 6, 6]
    phase_duration_ms: [3000, 1000, 10000]


